### ISSUE TITLE
Error in extension when Toggle button is clicked

### ISSUE THREAD

**Issue by Tony20221** [pathakshashank17/Bordify#1]
Error in extension when Toggle button is clicked

![image](https://user-images.githubusercontent.com/99626433/154863112-782d87d7-5418-4c17-9866-574228ccc0a3.png)

**Comment by pathakshashank17** [comment]
Hey! Thanks for raising an issue.

Does this error occur on all pages or only on Google Chrome's internal pages (internal pages mean pages like settings page, new tab, etc)?

**Comment by Tony20221** [comment]
It's working now.
